resolver: lts-12.0
packages:
- '.'
allow-newer: true
extra-deps:
    - SDL-0.6.6.0
    - gauge-0.2.3
    - bench-graph-0.1.3
    - Chart-1.9
    - Chart-diagrams-1.9
    - SVGFonts-1.6.0.3

flags: {}
extra-package-dbs: []
rebuild-ghc-options: true
# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include
